/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthNativeCallbackRouteImport } from './routes/auth.native-callback'
import { Route as ApiWebTtsRouteImport } from './routes/api/web/tts'
import { Route as ApiWebTranscribeRouteImport } from './routes/api/web/transcribe'
import { Route as ApiWebHistoryRouteImport } from './routes/api/web/history'
import { Route as ApiWebChatRouteImport } from './routes/api/web/chat'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNativeCallbackRoute = AuthNativeCallbackRouteImport.update({
  id: '/auth/native-callback',
  path: '/auth/native-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebTtsRoute = ApiWebTtsRouteImport.update({
  id: '/api/web/tts',
  path: '/api/web/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebTranscribeRoute = ApiWebTranscribeRouteImport.update({
  id: '/api/web/transcribe',
  path: '/api/web/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebHistoryRoute = ApiWebHistoryRouteImport.update({
  id: '/api/web/history',
  path: '/api/web/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebChatRoute = ApiWebChatRouteImport.update({
  id: '/api/web/chat',
  path: '/api/web/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/api/web/chat': typeof ApiWebChatRoute
  '/api/web/history': typeof ApiWebHistoryRoute
  '/api/web/transcribe': typeof ApiWebTranscribeRoute
  '/api/web/tts': typeof ApiWebTtsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/api/web/chat': typeof ApiWebChatRoute
  '/api/web/history': typeof ApiWebHistoryRoute
  '/api/web/transcribe': typeof ApiWebTranscribeRoute
  '/api/web/tts': typeof ApiWebTtsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/native-callback': typeof AuthNativeCallbackRoute
  '/api/web/chat': typeof ApiWebChatRoute
  '/api/web/history': typeof ApiWebHistoryRoute
  '/api/web/transcribe': typeof ApiWebTranscribeRoute
  '/api/web/tts': typeof ApiWebTtsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/native-callback'
    | '/api/web/chat'
    | '/api/web/history'
    | '/api/web/transcribe'
    | '/api/web/tts'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/native-callback'
    | '/api/web/chat'
    | '/api/web/history'
    | '/api/web/transcribe'
    | '/api/web/tts'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth/native-callback'
    | '/api/web/chat'
    | '/api/web/history'
    | '/api/web/transcribe'
    | '/api/web/tts'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthNativeCallbackRoute: typeof AuthNativeCallbackRoute
  ApiWebChatRoute: typeof ApiWebChatRoute
  ApiWebHistoryRoute: typeof ApiWebHistoryRoute
  ApiWebTranscribeRoute: typeof ApiWebTranscribeRoute
  ApiWebTtsRoute: typeof ApiWebTtsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/native-callback': {
      id: '/auth/native-callback'
      path: '/auth/native-callback'
      fullPath: '/auth/native-callback'
      preLoaderRoute: typeof AuthNativeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web/tts': {
      id: '/api/web/tts'
      path: '/api/web/tts'
      fullPath: '/api/web/tts'
      preLoaderRoute: typeof ApiWebTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web/transcribe': {
      id: '/api/web/transcribe'
      path: '/api/web/transcribe'
      fullPath: '/api/web/transcribe'
      preLoaderRoute: typeof ApiWebTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web/history': {
      id: '/api/web/history'
      path: '/api/web/history'
      fullPath: '/api/web/history'
      preLoaderRoute: typeof ApiWebHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web/chat': {
      id: '/api/web/chat'
      path: '/api/web/chat'
      fullPath: '/api/web/chat'
      preLoaderRoute: typeof ApiWebChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthNativeCallbackRoute: AuthNativeCallbackRoute,
  ApiWebChatRoute: ApiWebChatRoute,
  ApiWebHistoryRoute: ApiWebHistoryRoute,
  ApiWebTranscribeRoute: ApiWebTranscribeRoute,
  ApiWebTtsRoute: ApiWebTtsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
